### PR TITLE
Fix bug in parsing `#` token in TOML

### LINKED ISSUE #61: Bug in parsing `#` token in TOML
Hi,

Thanks for a great library.

I use `nanoserde` to load configuration from a TOML file. That file contains some comments but `nanoserde` does not support comments in TOML yet.

Could you please add it? Or let me know if you want a PR.

Thanks

### PR DESCRIPTION
**Pull request by hoangdt84**
Close #61

### CODE REVIEW

File: src/toml.rs [hunk 1]
```diff
@@ -473,6 +473,14 @@ impl TomlParser {
                     while self.cur != '\n' && self.cur != '\0' {
                         self.next(i);
                     }
+
+                    while self.cur == '\n'
```
Comment (not-fl3) [inline src/toml.rs:477]: I feel like those two while loops could be merged together?

Comment (hoangdt84) [reply src/toml.rs:477]: No we can't cause it fails in the following test. After the second `#` we have an empty line.
```
[[array]]
# a
name = "a" #aasdf

[[array]]
```

Comment (hoangdt84) [reply src/toml.rs:477]: The first loop removes any characters except LF.
The second loop finds the first char which is not space.

So I don't think we can merge them.
