### PR TITLE
add fixes for some clippy lints

### LINKED ISSUE #85: clippy::ignored-unit-patterns on `DeJson`
With Rust 1.73 and `clippy::pedantic` I'm getting this warning:

```
matching over `()` is more explicit

for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ignored_unit_patterns

`-W clippy::ignored-unit-patterns` implied by `-W clippy::pedantic`clippy

nanoserde_derive
proc_macro DeJson
```

Why?

### PR DESCRIPTION
**Pull request by knickish**
First commit closes #85, and fixes an issue with the no-std feature cfg. Also a couple clippy lints. 

Second commit fixes the `no_std` feature (which has apparently been broken for a while) and separates the `std` and `no_std` ci runs.

### CODE REVIEW

**Comment by knickish** [comment]
Also, probably a good time for a new version if you have time @not-fl3. There's a few fixes in there now that are not on `crates.io`

File: src/serde_json.rs [hunk 1]
```diff
@@ -899,7 +899,7 @@ where
 {
     fn ser_json(&self, d: usize, s: &mut SerJsonState) {
         s.out.push('[');
-        if self.len() > 0 {
+        if !self.is_empty() {
```
Comment (not-fl3) [inline src/serde_json.rs:902]: I do not think that !self.is_empty() is a lot better than self.len() > 0

File: src/serde_json.rs [hunk 2]
```diff
@@ -1156,16 +1156,14 @@ where
     fn ser_json(&self, d: usize, s: &mut SerJsonState) {
         s.out.push('{');
         let len = self.len();
-        let mut index = 0;
-        for (k, v) in self {
+        for (index, (k, v)) in self.iter().enumerate() {
```
Comment (not-fl3) [inline src/serde_json.rs:1159]: here as well, I am not quite convinced that there is anything wrong with index += 1

do we really need clippy to be forced on the whole crate?

**Comment by knickish** [comment]
@not-fl3 removed those changes you didn't like

**Comment by not-fl3** [comment]
> @not-fl3 removed those changes you didn't like

tbh I did not looked any further, I just wanted to illustrate the idea that we might be better off without clippy on the CI

**Comment by knickish** [comment]
Ah, I hadnt added it to CI, just ran it locally and implemented a couple things i thought looked helpful

**Comment by not-fl3** [comment]
> Ah, I hadnt added it to CI, just ran it locally and implemented a couple things i thought looked helpful

oh, my bad

**Review by not-fl3 — APPROVED** [review]

**Comment by knickish** [comment]
@not-fl3 could you do a release of the new version when you have time? thanks
